apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
  labels:
    app: flaskapp
spec:
  type: ClusterIP
  ports:
    - port: 8080    
  selector:
    app: flaskapp
    tier: frontend
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: flaskapp-dep
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
      containers:
      - image: spencer19/docker-flask-rest-nginx-uwsgi_flask:v1
        name: flaskapp
        env:
        - name: POSTGRES_DB_HOST
          value: postgres-svc
        - name: DATABASE_URL
          value: postgresql://postgres:docker@$(POSTGRES_DB_HOST):5432/postgres          
        ports:
        - containerPort: 8080
          name: flaskapp
      imagePullSecrets:
      - name: myregistrykey          