apiVersion: v1
kind: Service
metadata:
  name: my-postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: mypostgres
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: my-postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: mypostgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: mypostgres
    spec:
      containers:
      - image: postgres:latest
        name: mypostgres
        env:
        - name: POSTGRES_PASSWORD
          value: docker
        ports:
        - containerPort: 5432
          name: mypostgres
