apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-svc
  namespace: default
spec:
  type: NodePort # use ClusterIP as type here
  ports:
    - port: 80
      nodePort: 30003    
  selector:
    app: nginx-app 
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: spencer19/mynginx:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregistrykey          
