apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-svc
  namespace: default
spec:
  type: NodePort # use ClusterIP as type here
  ports:
    - port: 80
      nodePort: 30003    
  selector:
    app: nginx-app 
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
      - name: pv-storage-nginx
        persistentVolumeClaim:
          claimName: pv-claim-nginx
      containers:
      - name: nginx
        image: nginx:1.13.12
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/nginx"        
          name: pv-storage-nginx
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-nginx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/spencer/mypv/mynginxdata"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi                   
